version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install buildstock
          command: |
            pip install .[dev] --progress-bar off
      - run:
          name: Run PyTest
          command: |
            pytest -v
      - run:
          name: Run coverage tests
          when: always
          command: |
            set +e
            coverage run --source=buildstockbatch -m pytest > /dev/null 2>&1
            coverage report -m
            coverage html -d /tmp/coverage_report
      - run:
          name: Run style checks
          when: always
          command: |
            flake8 buildstockbatch
      - store_artifacts:
          path: /tmp/coverage_report
          destination: coverage-report
      - run:
          name: Build documentation
          when: always
          command: |
            cd docs
            make html
            mkdir /tmp/docs
            cp -r _build/html/* /tmp/docs
      - persist_to_workspace:
          root: /tmp
          paths:
            - docs
      - store_artifacts:
          path: /tmp/docs
          destination: docs

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
